import Head from 'next/head'
import { Button } from 'antd';




export const Header=(props:any)=>{

return (
    <div>
      <Head>
        <title>{props.title}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Button type="link" href="/">TODOアプリ</Button>
      <Button type="link" href="/weather">天気</Button>
      <Button type="link" href="/antdesign">アントデザイン</Button>
      <hr/>
    </div>
  )

}
