import type { NextPage } from 'next'
import Head from 'next/head'
import { useState } from 'react'
import styles from '../styles/Home.module.css'

const Home: NextPage = () => {
  const [text,setText]=useState("");
  const [task,setTask]=useState(["あああ","いいい"]);

  const handleText=(e)=>{
    setText(e.target.value);
  }

  const taskInput=()=>{
    if(text===""){
      return;
    }
    const newTask=[...task,text];
    setTask(newTask);
    setText("");
    console.log(task);
  }



  return (
    <div className={styles.container}>
      <Head>
        <title>TO DO アプリ</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <textarea value={text} onChange={handleText}/>
      <button onClick={taskInput}>タスク追加</button>
        {task.map((todo,index)=>{
          return(
          <div key={todo}>
            <h2>{todo}</h2>
          </div>
          )
        })}
    </div>
  )
}

export default Home
