import Head from 'next/head';
import { useState} from 'react';

const Weather= () => {
  const [city,setCity]=useState<string>("");
  const [weather,setWeather]=useState<weatherType>({
        country: "",
        cityName: "",
        temperature: "",
        conditionText: "",
        icon: ""});

  type weatherType = {
    country: string;
    cityName: string;
    temperature: string;
    conditionText: string;
    icon: string;
}

  const getWeather=(e:any)=>{
    e.preventDefault();
    fetch(`https://api.weatherapi.com/v1/current.json?key=d88509903e8144dd915101113222708&q=${city}&aqi=no`)
    .then(res=>res.json())
    .then(data=>{
                setWeather({
                    country: data.location.country,
                    cityName: data.location.name,
                    temperature: data.current.temp_c,
                    conditionText: data.current.condition.text,
                    icon: data.current.condition.icon
                })
            })
  }

  return(
    <div>
      <Head>
        <title>現在の天気</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <a href="/">TODOアプリ{" "}</a>
      <a href="/weather">天気</a>
      <hr/>

    <h1>現在の天気</h1>
    <form>
      <input type="text" placeholder='都市名を英語入力' onChange={(e)=>setCity(e.target.value)}/>
      <button type="submit" onClick={getWeather}>天気を見る</button>
    </form>
    <div>
            {weather.country &&
                <div>{weather.country}</div>
            }
            {weather.cityName &&
                <div>{weather.cityName}</div>
            }
            {weather.temperature &&
                <div>{weather.temperature} <span>°C</span></div>
            }
            {weather.conditionText &&
                <div>
                    <img src={weather.icon} alt="icon"/>
                    <span>{weather.conditionText}</span>
                </div>
            }
        </div>
    </div>
  )
}


export default Weather
